spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MoneyMinderDB?characterEncoding=UTF-8&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      useSSL: false
      allowPublicKeyRetrieval: true

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true
    format_sql: true


logging:
  level:
    org.hibernate.type.descriptor.sql: trace

jwt:
  secret:
    key: x!A%D*G-KaPdSgVkYp3s5v8y/B?E(H+M


